const DatabaseLoggerOperations = {
    DATABASE_CREATE_ATTEMPT: 'DATABASE_CREATE_OPERATION_ATTEMPT',
    DATABASE_READ_ATTEMPT: 'DATABASE_READ_OPERATION_ATTEMPT',
    DATABASE_UPDATE_ATTEMPT: 'DATABASE_UPDATED_OPERATION_ATTEMPT',
    DATABASE_DELETE_ATTEMPT: 'DATABASE_DELETE_OPERATION_ATTEMPT',

    DATABASE_CREATE_SUCCESSFUL: 'DATABASE_CREATE_OPERATION_SUCCESSFUL',
    DATABASE_READ_SUCCESSFUL: 'DATABASE_READ_OPERATION_SUCCESSFUL',
    DATABASE_UPDATE_SUCCESSFUL: 'DATABASE_UPDATED_OPERATION_SUCCESSFUL',
    DATABASE_DELETE_SUCCESSFUL: 'DATABASE_DELETE_OPERATION_SUCCESSFUL',
};

const ServiceLoggerOperations = {
    CREATE_OPERATION: 'CREATE_CLIENT_OPERATION',
    VALIDATE_SECRETE_OPERATION: 'VALIDATE_SECRET_OPERATION',
    SECRET_VALIDATION_FAILED: 'SECRET_VALIDATION_FAILED',
};

export const LoggerOperations = { ...DatabaseLoggerOperations, ...ServiceLoggerOperations };
