const DatabaseLoggerOperations = {
    DATABASE_CREATE_ATTEMPT: 'DATABASE_CREATE_OPERATION_ATTEMPT',
    DATABASE_READ_ATTEMPT: 'DATABASE_READ_OPERATION_ATTEMPT',
    DATABASE_UPDATE_ATTEMPT: 'DATABASE_UPDATED_OPERATION_ATTEMPT',
    DATABASE_DELETE_ATTEMPT: 'DATABASE_DELETE_OPERATION_ATTEMPT',

    DATABASE_CREATE_SUCCESSFUL: 'DATABASE_CREATE_OPERATION_SUCCESSFUL',
    DATABASE_READ_SUCCESSFUL: 'DATABASE_READ_OPERATION_SUCCESSFUL',
    DATABASE_UPDATE_SUCCESSFUL: 'DATABASE_UPDATED_OPERATION_SUCCESSFUL',
    DATABASE_DELETE_SUCCESSFUL: 'DATABASE_DELETE_OPERATION_SUCCESSFUL',
};

const ServiceLoggerOperations = {
    CREATE_USER_OPERATION: 'CREATE_USER_OPERATION',
    LOGIN_OPERATION: 'LOGIN_OPERATION',
    VALIDATE_OPERATION: 'VALIDATE_OPERATION',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    VALIDATE_CREDENTIALS_OPERATION: 'VALIDATE_CREDENTIALS_OPERATION',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    VALIDATE_TOKEN_OPERATION: 'VALIDATE_TOKEN_OPERATION',
};

export const LoggerOperations = {
    ...DatabaseLoggerOperations,
    ...ServiceLoggerOperations,
};
