const DatabaseLoggerOperations = {
    DATABASE_CREATE_ATTEMPT: 'DATABASE_CREATE_OPERATION_ATTEMPT',
    DATABASE_READ_ATTEMPT: 'DATABASE_READ_OPERATION_ATTEMPT',
    DATABASE_UPDATE_ATTEMPT: 'DATABASE_UPDATED_OPERATION_ATTEMPT',
    DATABASE_DELETE_ATTEMPT: 'DATABASE_DELETE_OPERATION_ATTEMPT',

    DATABASE_CREATE_SUCCESSFUL: 'DATABASE_CREATE_OPERATION_SUCCESSFUL',
    DATABASE_READ_SUCCESSFUL: 'DATABASE_READ_OPERATION_SUCCESSFUL',
    DATABASE_UPDATE_SUCCESSFUL: 'DATABASE_UPDATED_OPERATION_SUCCESSFUL',
    DATABASE_DELETE_SUCCESSFUL: 'DATABASE_DELETE_OPERATION_SUCCESSFUL',
};

const ServiceLoggerOperations = {
    CLIENT_REPORT_OPERATION_START: 'CLIENT_REPORT_OPERATION_START',
    CLIENT_REPORT_OPERATION_SUCCESSFUL: 'CLIENT_REPORT_OPERATION_SUCCESSFUL',
    USER_REPORT_OPERATION_START: 'USER_REPORT_OPERATION_START',
    USER_REPORT_OPERATION_SUCCESSFUL: 'USER_REPORT_OPERATION_SUCCESSFUL',
    SHORTIFY_REPORT_OPERATION_START: 'SHORTIFY_REPORT_OPERATION_START',
    SHORTIFY_REPORT_OPERATION_SUCCESSFUL: 'SHORTIFY_REPORT_OPERATION_SUCCESSFUL',
    ACTIVITY_REPORT_OPERATION_START: 'ACTIVITY_REPORT_OPERATION_START',
    ACTIVITY_REPORT_OPERATION_SUCCESSFUL: 'ACTIVITY_REPORT_OPERATION_SUCCESSFUL',
    TAG_USER_OPERATION_START: 'TAG_USER_OPERATION_START',
    TAG_USER_OPERATION_SUCCESSFUL: 'TAG_USER_OPERATION_SUCCESSFUL',
    TAG_USER_RECOVERY_OPERATION_START: 'TAG_USER_RECOVERY_OPERATION_START',
    CALL_AUTH_SERVICE_ATTEMPT: 'GRPC_CALL_AUTH_SERVICE_ATTEMPT',
    CALL_AUTH_SERVICE_SUCCESSFUL: 'GRPC_CALL_AUTH_SERVICE_SUCCESSFUL',
    FORBIDDEN_RESOURCE_FOR_USER: 'FORBIDDEN_RESOURCE_FOR_USER',
    NOT_FOUND_RESOURCE: 'NOT_FOUND_RESOURCE',
};

export const LoggerOperations = { ...DatabaseLoggerOperations, ...ServiceLoggerOperations };
