export const LoggerOperations = {
    CALL_SHORTIFY_SERVICE_ATTEMPT: 'GRPC_CALL_SHORTIFY_SERVICE_ATTEMPT',
    CALL_AUTH_SERVICE_ATTEMPT: 'GRPC_CALL_AUTH_SERVICE_ATTEMPT',
    CALL_CLIENT_SERVICE_ATTEMPT: 'GRPC_CALL_CLIENT_SERVICE_ATTEMPT',

    CALL_SHORTIFY_SERVICE_SUCCESSFUL: 'GRPC_CALL_SHORTIFY_SERVICE_SUCCESSFUL',
    CALL_AUTH_SERVICE_SUCCESSFUL: 'GRPC_CALL_AUTH_SERVICE_SUCCESSFUL',
    CALL_CLIENT_SERVICE_SUCCESSFUL: 'GRPC_CALL_CLIENT_SERVICE_SUCCESSFUL',
};
