@hostname = localhost
@port = 3000
@endpoint = client
@host = {{hostname}}:{{port}}/{{endpoint}}
@content_type = application/json

@auth_method = Bearer
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDU1OTYwYmFiYWI4MjA2MDAyODk3YTYiLCJlbWFpbCI6ImZpbGlwZUB0ZXN0ZTIuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNTY1ODkwOTEzfQ.4uu_Ndv54As4i8HqSkUlrjYNglG-yLlLWKf7sjgcolw

### Create

POST http://{{host}} HTTP/1.1
Content-Type: {{content_type}}
Authorization: {{auth_method}} {{token}}

{
	"name": "Test Client",
	"location":  {
		"address": "Test address, 123",
		"city": "Testville",
		"province": "TestLand",
		"country": "Test",
		"postal_code": "TST-123"
	}
}

###
