@hostname = localhost
@port = 3001

@host = {{hostname}}:{{port}}/api/v1

@content_type = application/json

@auth_method = Bearer
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjQ3ZjdkM2QyMTdkODEwMmM2NGUzOTAiLCJlbWFpbCI6ImZpbGlwZUB0ZXN0ZTIuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjAwMjY0MTcwfQ.YlYGZ3hWQYaa3_PcAvAzeN0pwvTd6x8w9w9KVqOlX4g
@tac = OQwatsbWR
@campaign = test
@grouptype = campaign
@keyvalue1 = Language
@keyvalue2 = Learn

### Get Link
GET http://{{host}}/shortify/{{tac}} HTTP/1.1
Authorization: {{auth_method}} {{token}}

### Get Report Links
GET http://{{host}}/shortify/report/links HTTP/1.1
Authorization: {{auth_method}} {{token}}

#### Get Report Links by group
GET http://{{host}}/shortify/report/links/group?by={{grouptype}} HTTP/1.1
Authorization: {{auth_method}} {{token}}

#### Get Report Links by tag
GET http://{{host}}/shortify/report/links/tag?key={{keyvalue1}}&key={{keyvalue2}} HTTP/1.1
Authorization: {{auth_method}} {{token}}

#### Get Autocomplete Tags
GET http://{{host}}/tags/autocomplete HTTP/1.1
Authorization: {{auth_method}} {{token}}
